package com.no5619.umirecorder.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.List;

@Data
@NoArgsConstructor
@Entity
@Table(name = "users")
public class UserEntity {
	  @Id
	  @GeneratedValue(strategy = GenerationType.IDENTITY) //AutogeneratedId
	  private int id;
	  private String name;
	  private String email;
	  private String password;

	  @ManyToMany(fetch = FetchType.EAGER)
	  @JoinTable(
			  name = "user_roles", 
			  joinColumns = @JoinColumn(name = "user_id", referencedColumnName = "id"),
	          inverseJoinColumns = @JoinColumn(name = "role_id", referencedColumnName = "id")
	  )
	  private List<Role> roles = new ArrayList<>();
	  	
}